name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    # TODO(jpoole): set this back to ubuntu-latest once https://github.com/actions/virtual-environments/issues/1816 lands
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: delete-excluded-dirs
        # This directory is deliberately broken to test the compile warnings we get. We can't exclude this in the normal
        # way: https://github.com/golangci/golangci-lint/issues/301
        run: "rm -rf tools/please_go_install/test_data"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
          args: src/... tools/...
